package com.example.firebaseapp.ui.theme

import androidx.compose.ui.graphics.Color

// LIGHT COLORS
val primaryLight = Color(0xFF6D5E10)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFDE88E)
val onPrimaryContainerLight = Color(0xFF584B00)
val secondaryLight = Color(0xFF675E3D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF2E6BB)
val onSecondaryContainerLight = Color(0xFF524A2A)
val tertiaryLight = Color(0xFF506528)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD8F2A5)
val onTertiaryContainerLight = Color(0xFF3E5216)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF9EE)
val onBackgroundLight = Color(0xFF1D1B15)
val surfaceLight = Color(0xFFFFF9EE)
val onSurfaceLight = Color(0xFF1D1B15)
val surfaceVariantLight = Color(0xFFEAE2CF)
val onSurfaceVariantLight = Color(0xFF4B4738)
val outlineLight = Color(0xFF7C7767)
val outlineVariantLight = Color(0xFFCDC6B3)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF33302A)
val inverseOnSurfaceLight = Color(0xFFF6F0E6)
val inversePrimaryLight = Color(0xFFDAC670)
val surfaceDimLight = Color(0xFFDFD9CF)
val surfaceBrightLight = Color(0xFFFFF9EE)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF9F3E9)
val surfaceContainerLight = Color(0xFFF3EDE3)
val surfaceContainerHighLight = Color(0xFFEDE7DD)
val surfaceContainerHighestLight = Color(0xFFE8E2D8)

// DARK COLORS
val primaryDark = Color(0xFFFFFFFF)
val onPrimaryDark = Color(0xFF393000)
val primaryContainerDark = Color(0xFFE9D47C)
val onPrimaryContainerDark = Color(0xFF4A3F00)
val secondaryDark = Color(0xFFD2C69D)
val onSecondaryDark = Color(0xFF373013)
val secondaryContainerDark = Color(0xFF443D1E)
val onSecondaryContainerDark = Color(0xFFDCD0A7)
val tertiaryDark = Color(0xFFFFFFFF)
val onTertiaryDark = Color(0xFF243600)
val tertiaryContainerDark = Color(0xFFC4DE92)
val onTertiaryContainerDark = Color(0xFF32450A)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF15130E)
val onBackgroundDark = Color(0xFFE8E2D8)
val surfaceDark = Color(0xFF15130E)
val onSurfaceDark = Color(0xFFE8E2D8)
val surfaceVariantDark = Color(0xFF4B4738)
val onSurfaceVariantDark = Color(0xFFCDC6B3)
val outlineDark = Color(0xFF96907F)
val outlineVariantDark = Color(0xFF4B4738)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE8E2D8)
val inverseOnSurfaceDark = Color(0xFF33302A)
val inversePrimaryDark = Color(0xFF6D5E10)
val surfaceDimDark = Color(0xFF15130E)
val surfaceBrightDark = Color(0xFF3B3932)
val surfaceContainerLowestDark = Color(0xFF100E09)
val surfaceContainerLowDark = Color(0xFF1D1B15)
val surfaceContainerDark = Color(0xFF212019)
val surfaceContainerHighDark = Color(0xFF2C2A23)
val surfaceContainerHighestDark = Color(0xFF37352E)